periods:
  n: 8
  t: 84

settings:
  eom:
    price_cap: .inf
  cm:
    volume: 20000.0

iesopt:
  config:
    general.verbosity.core: warning
    general.verbosity.solver: off
  parameters:
    prices:
      ch4: 32.4
      co2: 150.0
    emission_factors:
      ch4_co2: 0.154944 #0.202

rho:
  initial: 5.0

agents:
  thermal:
    config: opt/thermal.iesopt.yaml
    lifetime: 25
    wacc: 0.07
    parameters:
      p_nom: 2811.1
      p_nom_invest: 50000.0
      efficiency: 0.59
      fuelprice: prm.prices.ch4
      co2price: prm.prices.co2
      emission_factor_co2: prm.emission_factors.ch4_co2
      capex: 904650  #815000.0 * 1.11
      opex_fom: 29859 # 26900.0 * 1.11
      opex_vom: 4.551 # 4.1 * 1.11
      derating: 0.94

  wind:
    config: opt/renewable.iesopt.yaml
    lifetime: 25
    wacc: 0.07
    parameters:
      p_nom: 9000.0
      p_nom_invest: 30000.0
      availability_factor: wind
      capex: 990000.0
      opex_fom: 1592.0
      opex_vom: 0.0
      derating: 0.07
      tariff: 0.0

  solar:
    config: opt/renewable.iesopt.yaml
    lifetime: 25
    wacc: 0.07
    parameters:
      p_nom: 12000.257
      p_nom_invest: 30000.0
      availability_factor: solar
      capex: 330000.0
      opex_fom: 8100.0
      opex_vom: 0.0
      derating: 0.01
      tariff: 0.0

  storage:
    config: opt/storage.iesopt.yaml
    lifetime: 15
    wacc: 0.07
    parameters:
      p_nom: 67.758
      hours: 4.0
      efficiency: 0.92
      capex: 627122.0
      opex_fom: 15678.0
      opex_vom: 0.0
      derating: 0.57  

  demand:
    config: opt/demand.iesopt.yaml
    parameters:
      demand: demand
